// benchmarks/search-results/solid/components/SearchResultsItem.jsx
import { createSignal } from "solid-js";

export default function Item({ item }) {
  const [purchased, setPurchased] = createSignal(false);

  return (
    <div
      class="search-results-item"
      style={{ "background-color": purchased() ? "#f1c40f" : "" }}
    >
      <h2 textContent={item().title} />

      <div class="lvpic pic img left">
        <div class="lvpicinner full-width picW">
          <a href={"/buy/" + item().id} class="img imgWr2">
            <img src={item().image} alt={item().title} />
          </a>
        </div>
      </div>

      <span class="price" textContent={item().price} />

      {purchased() ? (
        <div class="purchased">Purchased!</div>
      ) : (
        <button
          class="buy-now"
          type="button"
          onClick={() => setPurchased(true)}
        >
          Buy now!
        </button>
      )}
    </div>
  );
};

// benchmarks/search-results/svelte/components/SearchResultsItem.svelte
<script>
  export let item;
  let purchased = false;
</script>

<div
  className="search-results-item"
  style="background-color: {purchased ? '#f1c40f' : ''}">
  <h2>{item.title}</h2>

  <div className="lvpic pic img left">
    <div className="lvpicinner full-width picW">
      <a href="/buy/{item.id}" className="img imgWr2">
        <img src={item.image} alt={item.title} />
      </a>
    </div>
  </div>

  <span className="price">{item.price}</span>

  {#if purchased}
    <div className="purchased">Purchased!</div>
  {:else}
    <button
      className="buy-now"
      type="button"
      on:click={() => (purchased = true)}>
      Buy now!
    </button>
  {/if}
</div>
