// benchmarks/color-picker/vue/client.jsx
var Vue = require("vue").default;
var App = require("./components/App").default;

var mountNode = document.getElementById("mount");

if (window.colors) {
  var colors = window.colors;
  const app = new Vue({
    render(h) {
      return <App colors={colors} />;
    }
  });

  app.$mount("#mount");

  console.log("Re-rendering on client completed");
}

window.addBench("vue", function(el, colors) {
  var widget;
  var currentDone;
  var selectedColorIndex = 0;

  function onMount(instance) {
    widget = instance;
  }

  // function onUpdate() {
  //     currentDone();
  // }

  const app = new Vue({
    data: {
      colors: colors
    },

    render(h) {
      return <App colors={colors} handleMount={onMount} />;
    }
  });

  app.$mount(el);

  return function(done) {
    widget.selectedColorIndex = ++selectedColorIndex % colors.length;
    widget.$nextTick(done);
  };
});

// benchmarks/color-picker/solid/client.jsx
import { hydrate, render } from "solid-js/web";
import App from "./components/App";

const mountNode = document.getElementById("mount");

if (window.colors) {
  hydrate(() => <App colors={window.colors} />, mountNode);

  console.log("Re-rendering on client completed");
}

window.addBench("solid", function(el, colors) {
  let setSelectedColorIndex;
  let selectedColorIndex = 0;

  render(
    () => <App colors={colors} onMount={_set => (setSelectedColorIndex = _set)} />,
    el
  );

  return done => {
    setSelectedColorIndex(++selectedColorIndex % colors.length);
    done();
  };
});
