// benchmarks/search-results/svelte/components/SearchResultsItem.svelte
<script>
  export let item;
  let purchased = false;
</script>

<div
  className="search-results-item"
  style="background-color: {purchased ? '#f1c40f' : ''}">
  <h2>{item.title}</h2>

  <div className="lvpic pic img left">
    <div className="lvpicinner full-width picW">
      <a href="/buy/{item.id}" className="img imgWr2">
        <img src={item.image} alt={item.title} />
      </a>
    </div>
  </div>

  <span className="price">{item.price}</span>

  {#if purchased}
    <div className="purchased">Purchased!</div>
  {:else}
    <button
      className="buy-now"
      type="button"
      on:click={() => (purchased = true)}>
      Buy now!
    </button>
  {/if}
</div>

// benchmarks/search-results/inferno/components/SearchResultsItem.jsx
var Inferno = require("inferno");
var Component = Inferno.Component;
var createVNode = Inferno.createVNode;
var linkEvent = Inferno.linkEvent;

function handleBuyButtonClick(instance, event) {
  instance.setState({ purchased: true });
}

module.exports = class extends Component {
  constructor(props) {
    super(props);

    this.state = {
      purchased: false
    };
  }

  componentWillReceiveProps(props) {
    this.setState({
      purchased: false
    });
  }

  render() {
    var item = this.props.item;
    var style = { "background-color": this.state.purchased ? "#f1c40f" : "" };

    return (
      <div className="search-results-item" style={style}>
        <h2>{item.title}</h2>

        <div className="lvpic pic img left">
          <div className="lvpicinner full-width picW">
            <a href={"/buy/" + item.id} className="img imgWr2">
              <img src={item.image} alt={item.title} />
            </a>
          </div>
        </div>

        <span className="price">{item.price}</span>

        {this.state.purchased ? (
          <div className="purchased">Purchased!</div>
        ) : (
          <button
            className="buy-now"
            type="button"
            onClick={linkEvent(this, handleBuyButtonClick)}
          >
            Buy now!
          </button>
        )}
      </div>
    );
  }
};
