// benchmarks/search-results/vue/client.jsx
var Vue = require("vue").default;
var App = require("./components/App").default;

var mountNode = document.getElementById("searchResultsMount");

if (mountNode) {
  const app = new Vue({
    render(h) {
      return <App searchResultsData={window.searchResultsData} />;
    }
  });

  app.$mount("#searchResultsMount");

  console.log("Re-rendering on client completed");
}

window.addBench("vue", function(el, getNextSearchResults) {
  const app = new Vue({
    data: {
      searchResultsData: getNextSearchResults()
    },

    render(h) {
      var searchResultsData = this.searchResultsData;

      return <App searchResultsData={searchResultsData} />;
    },

    methods: {
      updateSearchResults(searchResultsData, done) {
        this.searchResultsData = searchResultsData;
        this.$nextTick(done);
      }
    }
  });

  app.$mount(el);

  return function(done) {
    app.updateSearchResults(getNextSearchResults(), done);
  };
});

// benchmarks/search-results/solid/client.jsx
import { hydrate, render } from "solid-js/web";
import App from "./components/App";

var mountNode = document.getElementById("searchResultsMount");

if (mountNode) {
  hydrate(() =>
    <App searchResultsData={window.searchResultsData} />,
    mountNode
  );

  console.log("Re-rendering on client completed");
}

window.addBench("solid", function(el, getNextSearchResults) {
  const res = getNextSearchResults();
  let setSearchResultsData;
  render(() => <App searchResultsData={res} onMount={_set => (setSearchResultsData = _set)} />, el);

  return function(done) {
    setSearchResultsData(getNextSearchResults())
    done();
  };
});
